# Generated by Django 4.2 on 2023-05-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
